### ISSUE TITLE
Why year/month/day?

### ISSUE THREAD

**Issue by ddavidebor** [zerodha/frappe-attachments-s3#33]
Hi,

Just a quick question.
Why using year/month/day in the name of the attachment?

David

**Comment by faztp12** [comment]
Maybe an option to set it as
root-folder/doctype/name/filename ?

I think the requirements for every one of us is going to be different 😕 
Best expose a key_generator hook function so we could customize independently ?

**Comment by ddavidebor** [comment]
That would be great!

**Comment by faztp12** [comment]
@ddavidebor i made a PR this, Please check #35

**Comment by ddavidebor** [comment]
Do you have a working example of a function I can use?
